import type { FirmnessLevel, FruitContent, QuizOption } from "./types";
const firmness: Record<"q01" | "q02" | "q03" | "q04" | "q05", { a: FirmnessLevel; b: FirmnessLevel } | undefined> = {
 q01: { a: "ripe", b: "very_firm" },
 q02: { a: "very_firm", b: "ripe" },
 q03: undefined,
 q04: { a: "beginning_to_soften", b: "ripe" },
 q05: undefined,
};
const option = <Q extends "q01" | "q02" | "q03" | "q04" | "q05">(id: "a" | "b", q: Q): QuizOption => {
 const level = firmness[q]?.[id];
 return { id, assetKey: `avocado.quiz.${q}.${id}`, accessibilityLabel: `Option ${id.toUpperCase()}`, ...(level ? { tactile: { kind: "firmness", level } as const } : {}) };
};
export const avocado: FruitContent = {
 presentation:"editorial-lab",slug:"avocado",name:"Avocado",theme:{primary:"#54851C",dark:"#123A20",soft:"#E9F4D4"},seo:{title:"How to Tell If an Avocado Is Ripe | Fruit Picking Guide",description:"Learn the quick checks for choosing a ripe Hass avocado, from gentle pressure to structural damage.",h1:"How to Tell If an Avocado Is Ripe"},hero:{eyebrow:"AVOCADO",title:"How to Tell If an Avocado Is Ripe",directAnswer:"A ripe Hass avocado should feel firm, but give slightly under gentle pressure.",primaryCta:"See the quick checks",note:"This guide focuses on Hass avocados. Other varieties may behave differently.",assetKey:"avocado.hero"},quickChecks:[{id:"press",label:"PRESS",summary:"Gentle give"},{id:"plan",label:"PLAN",summary:"Match your timing"},{id:"feel",label:"FEEL",summary:"Even firmness"},{id:"look",label:"LOOK",summary:"Color helps"},{id:"inspect",label:"INSPECT",summary:"Avoid structural damage"}],
 timingGuide:{title:"WHEN WILL YOU EAT IT?",intro:"Pick for when you plan to eat it. The ripest avocado isn't always the best choice.",colorNote:"Color can help, but it doesn't tell the whole story.",stages:[{label:"VERY FIRM",timing:"3–5 days",summary:"Still very firm. Give it more time at room temperature."},{label:"SOON",timing:"2–3 days",summary:"Beginning to soften. A good choice if you're eating it later."},{label:"TODAY",timing:"Ready to eat",summary:"Firm, but yields slightly to gentle palm pressure."},{label:"TOO SOFT",timing:"Past ideal stage",summary:"Very soft fruit should be inspected carefully before using."}]},
 pickingSections:[{id:"press",layout:"feature",assetKey:"avocado.picking.press",assetAlt:"An adult hand cradling a Hass avocado across the palm with broad, gentle contact",visualTreatment:"pressure",title:"Press gently",lead:"Use your palm, not your fingertips.",body:"Hold the avocado in your palm and apply gentle, even pressure. A ripe avocado should still feel firm, but it will yield slightly."},{id:"timing",layout:"text",title:"Match it to your timing",body:"Choose a firmer avocado when you have a few days, and one with a gentle give when you plan to eat it now.",principle:"The ripest avocado isn't always the best choice."},{id:"damage",layout:"comparison",comparison:{detail:"surface",samples:[{assetKey:"avocado.picking.scuff",alt:"A Hass avocado with a minor surface scuff",label:"MINOR SCUFF"},{assetKey:"avocado.picking.damage",alt:"The matching Hass avocado with a localized structural dent",label:"STRUCTURAL DAMAGE"}]},title:"Cosmetic mark or real damage?",body:"Pay more attention to deep dents, localized soft pockets, or areas much softer than the rest.",principle:"Don't confuse ugly with damaged."},{id:"shape",layout:"detail",comparison:{detail:"outline",samples:[{assetKey:"avocado.picking.shapeNatural",alt:"A Hass avocado with its natural asymmetric outline intact",label:"NATURAL ASYMMETRY"},{assetKey:"avocado.picking.shapeCollapse",alt:"The matching Hass avocado with a shallow localized collapse on the lower-left contour",label:"LOCALIZED COLLAPSE"}]},title:"Check the shape",body:"Natural variation is normal; look for collapse or structural damage."},{id:"stem",layout:"detail",assetKey:"avocado.picking.stem",assetAlt:"Macro view of a tan attached stem button surrounded by intact, pebbled Hass avocado skin",visualTreatment:"stem-detail",title:"Check around the stem",body:"Look at the skin around the stem for signs of damage or decay.",conditionGuide:{avoidAssetKey:"avocado.picking.stemDamage",avoidAlt:"Matching stem macro with a localized sunken dark lesion and a small patch of mold around the attached stem",lookFor:"Intact surrounding skin. No obvious wounds, sunken patches or visible mold.",avoid:"Skip fruit with a sunken dark patch, visible mold or mushy skin around the stem.",note:"Leave the stem attached. Its brown color alone is not a spoilage test. Check ripeness with your palm: firm with a little give is ready; very firm needs time."}},{id:"color",layout:"statement",title:"Color helps. It doesn't decide.",body:"Hass avocados often darken, but use firmness as the final check."}],
 dontOverthink:[{label:"MINOR SCUFFS",summary:"Usually fine."},{label:"NATURAL ASYMMETRY",summary:"Completely normal."},{label:"THE DARKEST COLOR",summary:"Doesn't automatically mean best."},{label:"PERFECT-LOOKING SKIN",summary:"Doesn't guarantee an undamaged avocado."}],
 quiz:{stage:"compact-game",title:"TEST YOUR EYE",intro:"Think you've got it? Pick the avocado that best fits each situation.",completion:{eyebrow:"YOU'VE GOT IT",title:"You know what to look for.",summary:"A good avocado is about more than color. Match firmness, timing and overall condition.",takeaways:[{label:"PRESS",text:"Gentle give"},{label:"PLAN",text:"Match the timing"},{label:"FEEL",text:"Even firmness"},{label:"LOOK",text:"Color is secondary"},{label:"AVOID",text:"Suspicious soft spots and collapse"}]},questions:[
 {id:"q01-eat-tonight",question:"Which one would you eat tonight?",helperText:"You're looking for an avocado that's ready to eat now.",options:[option("a","q01"),option("b","q01")],correctOption:"a",optionExplanations:{a:"Firm with a little give. Ready for tonight.",b:"Very firm. Needs more time to ripen."},correctFeedback:"Good pick. This one is ready to eat now.",incorrectFeedback:"This one is still too firm for eating tonight. Give it more time to ripen.",learningPoint:"For eating today, choose an avocado that still feels firm but yields slightly to gentle pressure.",autoAdvanceOnCorrect:false},
 {id:"q02-gentle-press",question:"Which one feels riper?",helperText:"Imagine giving both avocados the same gentle palm pressure.",options:[option("a","q02"),option("b","q02")],correctOption:"b",optionExplanations:{a:"High resistance. Still very firm.",b:"Gentle give, while still firm."},correctFeedback:"That's the one. A slight give is the better sign of ripeness.",incorrectFeedback:"This one is still very firm. It likely needs more time.",learningPoint:"Use gentle, even palm pressure. Ripe doesn't mean mushy—it should still feel firm.",autoAdvanceOnCorrect:false},
 {id:"q03-cosmetic-damage",inspection:"surface",question:"Which one only has a minor scuff?",helperText:"Look for the difference between a cosmetic mark and structural damage.",options:[option("a","q03"),option("b","q03")],correctOption:"a",optionExplanations:{a:"A shallow surface scuff; the contour is intact.",b:"A deeper dent disrupts the surface."},correctFeedback:"Correct. A small surface scuff can be cosmetic.",incorrectFeedback:"Look more closely at the structure. This avocado has a deeper damaged area.",learningPoint:"Don't confuse ugly with damaged. Deep dents and localized soft spots matter more than small surface marks.",autoAdvanceOnCorrect:false},
 {id:"q04-buy-for-later",question:"You want to eat it in 2–3 days. Which one should you buy?",helperText:"Pick for your timing, not maximum ripeness.",options:[option("a","q04"),option("b","q04")],correctOption:"a",optionExplanations:{a:"Beginning to soften. Better for 2–3 days from now.",b:"Already ripe. Better for eating today."},correctFeedback:"Exactly. This one better matches your timing.",incorrectFeedback:"This one is already ready today. For 2–3 days from now, choose a firmer avocado.",learningPoint:"The ripest avocado isn't always the best choice. Buy for when you plan to eat it.",autoAdvanceOnCorrect:false},
 {id:"q05-final-pick",inspection:"outline",question:"FINAL PICK Both are ripe. Which one would you choose?",helperText:"Choose the avocado with the healthier structure.",options:[option("a","q05"),option("b","q05")],correctOption:"a",optionExplanations:{a:"Natural asymmetry with an intact outline.",b:"A localized collapse interrupts the outline."},correctFeedback:"Great final pick. Both are ripe, but this one has the healthier overall structure.",incorrectFeedback:"Ripeness isn't the only thing to check. This avocado has a localized area that may indicate damage.",learningPoint:"When both are ripe, choose the one with even firmness and no suspicious soft spots, dents or localized collapse.",autoAdvanceOnCorrect:false}]},
 nutrition:{basis:"per 100g",metrics:[{label:"Calories",value:"160 kcal"},{label:"Fat",value:"14.7 g"},{label:"Carbs",value:"8.5 g"},{label:"Fiber",value:"6.7 g"}]},faq:[{question:"Is color enough to tell whether an avocado is ripe?",answer:"No. Hass avocados often darken as they ripen, but firmness is the better final check. Choose one that is still firm and yields slightly to gentle palm pressure."},{question:"Should I avoid an avocado with a small surface scuff?",answer:"Not necessarily. A minor scuff can be cosmetic. Avoid deeper dents, localized soft pockets, or signs of structural collapse instead."}],relatedFruits:["kiwi","pomegranate","persimmon"],sources:[{label:"UC Davis — Avocado quality and stem-end rot",url:"https://postharvest.ucdavis.edu/produce-facts-sheets/avocado"},{label:"California Avocado Commission — Selecting ripe avocados",url:"https://californiaavocado.com/how-to/how-to-choose-and-use-an-avocado/"},{label:"USDA FoodData Central — FDC 171705",url:"https://fdc.nal.usda.gov/food-details/171705/nutrients"}]
};
