import type { FruitContent, QuizOption } from "./types";

const option = (id: "a" | "b"): QuizOption => ({
  id, assetKey: `kiwi.quiz.q01.${id}`, accessibilityLabel: `Option ${id.toUpperCase()}`,
  tactile: { kind: "firmness", level: id === "a" ? "ripe" : "very_firm",
    description: id === "a" ? "Slight give · still holds its shape" : "Very firm · almost no give" },
});

export const kiwi: FruitContent = {
  presentation: "editorial-lab", slug: "kiwi", name: "Kiwi",
  theme: { primary: "#78983A", dark: "#30401F", soft: "#E4EBCD" },
  seo: {
    title: "How to Tell If a Kiwi Is Ripe (5 Quick Checks)",
    description: "Check when green kiwi is ready to eat, learn how to ripen or store kiwi, and keep a whole batch from softening at once.",
    h1: "How to Tell If a Kiwi Is Ripe",
  },
  hero: {
    eyebrow: "GREEN / FUZZY KIWI", title: "How to Tell If a Kiwi Is Ripe",
    directAnswer: "A ripe green kiwi should feel plump and yield slightly to gentle pressure. If it is still very firm, let it ripen longer; if it feels mushy or has localized soft spots, inspect it carefully.",
    primaryCta: "Check if it's ready", secondaryCta: "Control the ripening", secondaryCtaHref: "#store",
    note: "This guide focuses on green / fuzzy kiwifruit. Gold varieties can ripen somewhat differently.", assetKey: "kiwi.hero",
  },
  quickChecks: [
    { id: "press", label: "PRESS", summary: "Gentle give" },
    { id: "plump", label: "PLUMP", summary: "Full, not shriveled" },
    { id: "check", label: "CHECK", summary: "Avoid soft pockets and bruises" },
    { id: "plan", label: "PLAN", summary: "Match firmness to when you'll eat it" },
    { id: "store", label: "STORE", summary: "Control the ripening speed" },
  ],
  timingGuide: {
    title: "HOW DOES IT FEEL?", intro: "Use light, even palm pressure. The feel tells you more than the brown skin or fuzz.",
    stages: [
      { label: "VERY FIRM", timing: "NOT YET", summary: "Almost no give. Still ripening; useful when you are not eating it immediately." },
      { label: "SLIGHT GIVE", timing: "READY TO EAT", summary: "Plump, yields gently and still holds its shape. It should not feel mushy." },
      { label: "VERY SOFT", timing: "EAT SOON / CHECK", summary: "Possibly past ideal. Inspect for bruising, local breakdown or excessive shriveling. Soft does not automatically mean rotten." },
    ],
  },
  pickingSections: [
    { id: "press", layout: "photo", title: "Press gently", lead: "Palm → light, even pressure → a little give.",
      body: "Cradle the kiwi in your palm. Apply light, even pressure with broad contact, then turn it to compare another area. Do not poke with your thumb or squeeze hard.",
      checks: { lookFor: "A little give all around, with structure remaining: ready to eat.", avoid: "Almost no give: wait. Mushiness or one unusually soft spot: check the condition." },
      assetKey: "kiwi.picking.press", assetAlt: "A whole green kiwi cradled gently in a hand with relaxed fingers", visualTreatment: "photo", visualCaption: "Broad contact · gentle pressure · no fingertip poke" },
    { id: "plump", layout: "photo", title: "Look for a plump kiwi", lead: "A full outline and healthy skin.",
      body: "Look around the whole fruit for a full, well-filled shape. Plumpness is a condition check; use gentle pressure to decide whether it is ready now.",
      checks: { lookFor: "Full structure and intact skin, without bruises.", avoid: "A shrunken outline or obvious folds. Inspect these more closely." },
      assetKey: "kiwi.quiz.q01.a", assetAlt: "A plump green kiwi with a full outline", visualTreatment: "photo", visualCaption: "Plump does not tell you firmness · check by touch" },
    { id: "check", layout: "comparison", title: "Watch for localized soft spots",
      body: "Gentle softening across the whole fruit can be normal ripening. One isolated area much softer than the rest may indicate bruising or physical damage. Compare the shape, then confirm the feel.",
      comparison: { detail: "whole", samples: [
        { assetKey: "kiwi.quiz.q02.a", alt: "A whole kiwi with an even, intact surface", label: "EVEN STRUCTURE · CHECK GENTLY" },
        { assetKey: "kiwi.quiz.q02.b", alt: "The same kiwi with one restrained localized bruise", label: "ONE LOCAL BRUISE · CHECK AGAIN" },
      ] } },
    { id: "wrinkles", layout: "comparison", title: "Check for wrinkling / shriveling",
      body: "Compare fullness, not the amount of fuzz. Noticeable folds and a shrunken outline call for a closer condition check; they are not proof of rot by themselves.",
      comparison: { detail: "whole", samples: [
        { assetKey: "kiwi.quiz.q01.a", alt: "A plump green kiwi with a full outline", label: "PLUMP · FULL SKIN" },
        { assetKey: "kiwi.picking.wrinkles", alt: "A noticeably shriveled green kiwi", label: "SHRIVELED · CHECK CONDITION" },
      ] } },
    { id: "fuzz", layout: "statement", title: "Fuzz doesn't tell you if it's ripe.",
      body: "Green kiwifruit naturally has fuzzy skin. How fuzzy it looks, or how dark the brown skin is, is not the useful household ripeness check.", principle: "Feel the firmness. Look for plumpness. Check the condition." },
    { id: "plan", layout: "text", title: "Pick for your timing",
      body: "Eating tonight? Choose a plump kiwi with slight give. Shopping for later? Include firmer fruit and keep it cold until you want it to ripen.",
      checks: { lookFor: "One ready now + firmer fruit for later.", avoid: "Buying the whole batch very soft when you cannot eat it soon." },
      principle: "Check the feel each day. A calendar cannot tell you exactly when it's ready." },
  ],
  dontOverthink: [
    { label: "MORE FUZZ", summary: "Doesn't mean less ripe." },
    { label: "DARKER BROWN SKIN", summary: "Isn't the main ripeness test." },
    { label: "THE SOFTEST KIWI", summary: "Isn't automatically the best purchase." },
    { label: "LEAVING THE WHOLE BOX OUT", summary: "Can make too many ripen together." },
  ],
  quiz: { stage: "compact-game", title: "TEST YOUR EYE", intro: "Choose the evidence or plan that fits the situation.",
    completion: { eyebrow: "YOU'VE GOT IT", title: "Pick it. Ripen it. Pace the batch.",
      summary: "Slight give for today. Firmer fruit for later. Ripen only what you'll eat soon.",
      takeaways: [
        { label: "PRESS", text: "Look for a slight give." }, { label: "PLUMP", text: "Avoid shriveled fruit." },
        { label: "CHECK", text: "Watch for abnormal soft spots." }, { label: "CONTROL", text: "Cold slows; ethylene speeds." },
        { label: "PLAN", text: "Ripen only what you'll eat soon." },
      ] },
    questions: [
      { id: "q01-eat-today", question: "Which kiwi would you eat today?", inspection: "whole",
        helperText: "Both look plump and healthy. Check firmness on each: the photos cannot tell you how they feel.",
        tactileInstruction: "Check firmness on both fruits. Compare the touch descriptions, then choose for today.",
        options: [option("a"), option("b")], correctOption: "a",
        optionExplanations: { a: "Slight give with structure remaining. Ready for today.", b: "Very firm with almost no give. Allow more time." },
        correctFeedback: "Yes. A has a little give and still holds its shape.", incorrectFeedback: "B is still very firm. Choose the kiwi with slight give for today.",
        learningPoint: "Feel for gentle give, not a change in skin color.", autoAdvanceOnCorrect: false },
      { id: "q02-soft-spot", question: "Which kiwi should you avoid buying?", intent: "avoid-buying", inspection: "whole",
        helperText: "Select the fruit with the concerning localized damage. Both images show the same type of kiwi.",
        options: [
          { id: "a", assetKey: "kiwi.quiz.q02.a", accessibilityLabel: "Option A" },
          { id: "b", assetKey: "kiwi.quiz.q02.b", accessibilityLabel: "Option B" },
        ], correctOption: "b",
        optionExplanations: { a: "An even outline and intact skin. This is the better buying choice.", b: "One localized depressed bruise. Choose another fruit." },
        correctFeedback: "Correct: avoid buying B. The local bruise is the warning sign.", incorrectFeedback: "A has the healthier structure. B is the fruit to avoid buying.",
        learningPoint: "A visible bruise is a condition cue. An unusually soft local pocket also needs checking by touch.", autoAdvanceOnCorrect: false },
      { id: "q03-ripen-faster", question: "You want this firm kiwi ready sooner. What should you do?",
        options: [{ id: "a", text: "Keep it in the refrigerator away from other fruit.", illustrations: ["kiwi.illustration.fridge"] }, { id: "b", text: "Put it at room temperature with an apple or banana.", illustrations: ["kiwi.illustration.bag"] }], correctOption: "b",
        optionExplanations: { a: "Cold storage slows ripening. Useful when you want more time.", b: "An apple or banana releases ethylene, helping a firm kiwi ripen faster." },
        correctFeedback: "Yes. Use room temperature with an apple or banana.", incorrectFeedback: "Refrigeration slows the process. Use room temperature with an apple or banana to speed it up.",
        learningPoint: "A paper bag with an apple or banana helps. Check the feel daily.", autoAdvanceOnCorrect: false },
      { id: "q04-batch", question: "Six kiwi are almost ripe, but you can only eat two soon. What's the better plan?",
        options: [{ id: "a", text: "Leave all six on the counter.", illustrations: ["kiwi.illustration.counter-six"] }, { id: "b", text: "Refrigerate the ripe/near-ripe fruit and only leave out the amount you plan to eat soon.", illustrations: ["kiwi.illustration.split-six"] }], correctOption: "b",
        optionExplanations: { a: "The whole batch will keep softening together.", b: "Cold slows further softening while you eat the small batch first." },
        correctFeedback: "That's the plan: eat a small batch and keep the rest cold.", incorrectFeedback: "Leaving all six out makes it harder to keep up. Refrigerate the fruit you will not eat soon.",
        learningPoint: "Cold slows ripening; it does not stop it completely. Keep checking the stored fruit.", autoAdvanceOnCorrect: false },
      { id: "q05-pick-and-plan", question: "You want one kiwi tonight and several for later. Which shopping plan is better?",
        options: [{ id: "a", text: "Buy every kiwi already very soft.", illustrations: ["kiwi.illustration.all-now"] }, { id: "b", text: "Choose one ready-to-eat kiwi plus firmer fruit for later.", illustrations: ["kiwi.illustration.now-later"] }], correctOption: "b",
        optionExplanations: { a: "A very soft batch gives you little flexibility.", b: "Slight give for tonight; firmer fruit can wait in the refrigerator." },
        correctFeedback: "Good plan. Match the firmness to when you will eat each fruit.", incorrectFeedback: "The softest batch is not the best fit here. Mix ready fruit with firmer fruit for later.",
        learningPoint: "Take out only the next 2–3 firm fruit when you are ready to ripen another batch.", autoAdvanceOnCorrect: false },
    ],
  },
  nutrition: {
    basis: "per 100g",
    metrics: [
      { label: "Calories", value: "65 kcal" },
      { label: "Carbohydrate", value: "13.8 g" },
      { label: "Fiber", value: "2.1 g" },
      { label: "Total sugars", value: "8.6 g" },
      { label: "Vitamin C", value: "58.8 mg" },
    ],
  },
  faq: [
    { question: "How soft should a ripe kiwi be?", answer: "A green kiwi should be plump and give slightly under gentle palm pressure, with structure remaining. Very soft fruit needs a condition check; it is not automatically rotten." },
    { question: "How long does a firm green kiwi take to ripen?", answer: "Often several days at room temperature. Starting firmness and room conditions vary, so check daily for slight give instead of relying on a fixed date." },
    { question: "Can I ripen kiwi faster?", answer: "Place firm kiwi in a paper bag with an apple or banana at room temperature, away from direct sunlight. Their ethylene helps accelerate ripening. Check daily." },
    { question: "Should ripe kiwi be refrigerated?", answer: "Yes, when you need more time. Cold slows further softening but does not stop it. Keep it separate from apples and bananas when you want to slow ripening." },
    { question: "What should I do if too many kiwi ripen at once?", answer: "Sort by firmness. Eat the softest sound fruit first, refrigerate ripe and firmer fruit, and take out only the next small batch you want to ripen." },
    { question: "Can I freeze ripe kiwi?", answer: "Yes. Peel and slice or chop sound ripe kiwi. Freeze the pieces on a tray, then transfer to a freezer container for smoothies, sorbets or blended drinks. Thawed kiwi will be softer than fresh fruit. Refrigerate any cut fruit you are not freezing in a covered container and use promptly." },
  ],
  sources: [
    { label: "UC Davis Postharvest — Kiwifruit quality and ethylene sensitivity", url: "https://postharvest.ucdavis.edu/produce-facts-sheets/kiwifruit" },
    { label: "Utah State University Extension — Kiwifruit selection", url: "https://extension.usu.edu/fscreate/files/handoutFFruitsKiwiHandout.pdf" },
    { label: "Zespri — Choosing, ripening and storing kiwifruit", url: "https://www.zespri.com/en-NZ/corporate-information/faqs" },
    { label: "Zespri — How to ripen kiwi and manage larger quantities", url: "https://www.zespri.com/en-US/blogdetail/how-do-i-ripen-kiwifruit" },
    { label: "Zespri — Freezing and cut-fruit storage", url: "https://www.zespri.com/en-US/blogdetail/how-to-store-kiwi-fruit-for-freshness-and-flavor" },
    { label: "USDA FoodData Central — FDC 2710831", url: "https://fdc.nal.usda.gov/food-details/2710831/nutrients" },
  ],
  relatedFruits: ["avocado", "pomegranate", "persimmon"],
};

export const kiwiStorage = {
  modes: [
    { id: "slow", title: "SLOW IT DOWN", place: "Refrigerator", cue: "Keep longer", text: "Keep large batches and ripe fruit cold to slow further softening. Separate them from apples and bananas when you do not want faster ripening." },
    { id: "normal", title: "RIPEN NORMALLY", place: "Counter", cue: "Eat soon", text: "Let a small batch of firm fruit ripen at room temperature, away from direct sunlight. Check for slight give each day." },
    { id: "fast", title: "SPEED IT UP", place: "Paper bag + apple / banana", cue: "Ready sooner", text: "Add an apple or banana to a paper bag with firm kiwi at room temperature. Their ethylene accelerates ripening; check daily." },
  ],
  rescue: [
    { title: "Sort by firmness", text: "Group into very soft, ready and still firm. Check the condition as you sort." },
    { title: "Eat the softest first", text: "Prioritize very soft fruit only while it is still in good condition." },
    { title: "Refrigerate the ripe ones", text: "Cold slows further softening and gives you more time." },
    { title: "Keep the firmer ones cold", text: "Take out only the amount you want to ripen next." },
    { title: "Freeze the excess", text: "Peel and cut sound ripe kiwi. Tray-freeze, then pack for smoothies or sorbets." },
  ],
};
